// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApplication1.Models
{
    [Index(nameof(CompetencyId), Name = "IX_Behavior_CompetencyId")]
    public partial class Behavior
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(2000)]
        
        [Display(Name="Kompetencja")]
        public string Name { get; set; }
        [StringLength(100)]

        [Display(Name="Uwagi")]
        public string Description { get; set; }
        public int CompetencyId { get; set; }

        [ForeignKey(nameof(CompetencyId))]
        [InverseProperty("Behavior")]
        public virtual Competency Competency { get; set; }
    }
}